
name: Compile Latex and upload PDF

on: push
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: constitution.tex
      - name: Upload compiled document
        uses: actions/upload-artifact@v3
        with:
          name: Compiled document
          path: ./constitution.pdf
